In [1]:
!pip install pandas-datareader

Requirement already satisfied: pandas-datareader in c:\programdata\anaconda3\lib\site-packages (0.10.0)
Requirement already satisfied: requests>=2.19.0 in c:\programdata\anaconda3\lib\site-packages (from pandas-datareader) (2.26.0)
Requirement already satisfied: pandas>=0.23 in c:\programdata\anaconda3\lib\site-packages (from pandas-datareader) (1.3.4)
Requirement already satisfied: lxml in c:\programdata\anaconda3\lib\site-packages (from pandas-datareader) (4.6.3)
Requirement already satisfied: numpy>=1.17.3 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.23->pandas-datareader) (1.20.3)
Requirement already satisfied: pytz>=2017.3 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.23->pandas-datareader) (2021.3)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.23->pandas-datareader) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas>=0.23->pandas-datareader) (1.16.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.19.0->pandas-datareader) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.19.0->pandas-datareader) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.19.0->pandas-datareader) (3.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.19.0->pandas-datareader) (2.0.4)

In [1]:
    # importa librerías
import pandas as pd
from pandas_datareader import wb
    # descarga data
data_gdp = wb.download(indicator='NY.GDP.PCAP.KD', country=[], start=1960, end=2020)
data_life = wb.download(indicator='SP.DYN.LE00.IN', country=[], start=1960, end=2020)
data_mort = wb.download(indicator='SH.DYN.NMRT', country=[], start=1960, end=2020)
data_pop = wb.download(indicator='SP.POP.TOTL', country=[], start=1960, end=2020)
    # combina un solo data frame
df1 = pd.concat([data_gdp, data_life.reindex(data_gdp.index), data_pop.reindex(data_gdp.index), data_mort.reindex(data_gdp.index)], axis=1)
    # depura
df = df1.dropna()
df

                                  NY.GDP.PCAP.KD  SP.DYN.LE00.IN  SP.POP.TOTL  \
country                     year
Africa Eastern and Southern 2019     1499.256275       64.005197  660046272.0
                            2018     1507.861055       63.648988  643090131.0
                            2017     1507.821357       63.246264  626392880.0
                            2016     1501.671310       62.787681  609978946.0
                            2015     1507.800256       62.259288  593871847.0
...                                          ...             ...          ...
Zimbabwe                    1969     1290.313227       56.656000    5111326.0
                            1968     1187.023436       56.362000    4941901.0
                            1967     1203.561658       56.034000    4779825.0
                            1966     1148.226118       55.671000    4623340.0
                            1965     1169.489415       55.274000    4471178.0

                                  SH.DYN.NMRT
country                     year
Africa Eastern and Southern 2019    24.387831
                            2018    24.938211
                            2017    25.480369
                            2016    26.014181
                            2015    26.601909
...                                       ...
Zimbabwe                    1969    31.700000
                            1968    31.700000
                            1967    31.800000
                            1966    32.000000
                            1965    32.400000

[9150 rows x 4 columns]